[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_lamport_transfer = "DZp6cD4Cf33hGkkiRvdWsp9gzwGb2T8Ebxf3fyYddeZU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/VikramR/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
